---
version: "3.9"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    ports:
      - 32400:32400
      # - 1900:1900/udp
      # - 3005:3005
      # # - 5353:5353/udp
      # - 8324:8324
      # - 32410:32410/udp
      # - 32412:32412/udp
      # - 32413:32413/udp
      # - 32414:32414/udp
      # - 32469:32469
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - plex:/config
      - plex_nfs:/data #path to media storage
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`plex.hogin.pro`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.routers.plex.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik"
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 16G
    networks:
      - plex


volumes:
  plex:
    name: plex

  plex_nfs:
    name: plex_nfs
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=fs01.msk.hogin.pro,rw"
      device: ":/mnt/home/media"
networks:
  plex:
    name: plex
